import type { Provider } from "../src/research";
// Optional runtime secrets; bindings/runtime types remain generated by Wrangler.
export type AiSecrets = {
  GEMINI_API_KEY?: string;
  OPENAI_API_KEY?: string;
  TAVILY_API_KEY?: string;
};
export type ResearchEnv = Env & AiSecrets;
export class ResearchError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
  }
}
export function providerConfig(env: ResearchEnv, provider: Provider) {
  if (provider === "OpenCode Go")
    throw new ResearchError(
      422,
      "OpenCode Go requiere confirmar que admite este uso. Elige Gemini u OpenAI.",
    );
  const key = provider === "Gemini" ? env.GEMINI_API_KEY : env.OPENAI_API_KEY;
  const model = provider === "Gemini" ? env.GEMINI_MODEL : env.OPENAI_MODEL;
  if (!key)
    throw new ResearchError(
      422,
      `Configura la clave de ${provider} en Cloudflare antes de investigar.`,
    );
  if (provider === "OpenAI" && env.ALLOW_PAID_AI !== "true")
    throw new ResearchError(
      422,
      "OpenAI está desactivado hasta autorizar y configurar su consumo de pago.",
    );
  return { provider, key, model };
}
export async function connections(env: ResearchEnv) {
  const month = new Date().toISOString().slice(0, 7);
  const usage = async (service: string) =>
    (
      await env.DB.prepare(
        "SELECT reserved FROM research_usage WHERE period=? AND service=?",
      )
        .bind(month, service)
        .first<{ reserved: number }>()
    )?.reserved ?? 0;
  return {
    providers: [
      {
        name: "Gemini",
        configured: !!env.GEMINI_API_KEY,
        model: env.GEMINI_MODEL,
        enabled: true,
      },
      {
        name: "OpenAI",
        configured: !!env.OPENAI_API_KEY,
        model: env.OPENAI_MODEL,
        enabled: env.ALLOW_PAID_AI === "true",
      },
      { name: "OpenCode Go", configured: false, model: "", enabled: false },
    ],
    search: {
      name: "Tavily",
      configured: !!env.TAVILY_API_KEY,
      used: await usage("search"),
      limit: Number(env.SEARCH_MONTHLY_LIMIT),
    },
    ai: { used: await usage("ai"), limit: Number(env.AI_MONTHLY_LIMIT) },
  };
}
export async function reserve(env: ResearchEnv, service: "ai" | "search") {
  const month = new Date().toISOString().slice(0, 7);
  const limit = Number(
    service === "ai" ? env.AI_MONTHLY_LIMIT : env.SEARCH_MONTHLY_LIMIT,
  );
  if (!Number.isSafeInteger(limit) || limit < 1)
    throw new ResearchError(429, "La cuota de investigación está desactivada.");
  const row = await env.DB.prepare(
    "INSERT INTO research_usage(period,service,reserved) VALUES (?,?,1) ON CONFLICT(period,service) DO UPDATE SET reserved=reserved+1 WHERE reserved < ? RETURNING reserved",
  )
    .bind(month, service, limit)
    .first();
  if (!row)
    throw new ResearchError(
      429,
      "Has alcanzado el límite mensual de investigación. Tus resultados guardados siguen disponibles.",
    );
}
